### ISSUE TITLE
ecr-credential-provider binaries as part of the release

### ISSUE THREAD

**Issue by dcarrion87** [kubernetes/cloud-provider-aws#633] opened 2023-07-22 11:55 UTC
Would be handy to have binaries for the ecr-credential-provider as part of the release similar to:

https://github.com/Fred78290/aws-ecr-credential-provider/releases

amd64 Compatible binaries for 1.25, 1.26 and 1.27 in particular.

Would save from having to compile separately.

**Comment by james-callahan** [comment] 2023-08-01 03:05
Duplicate of https://github.com/kubernetes/cloud-provider-aws/issues/512

**Closed** 2024-03-25 15:01 UTC
Labels: lifecycle/rotten, needs-triage
