### ISSUE TITLE
Race condition on updating LB's targetGroup for ETP=Local

### ISSUE THREAD

**Issue by kon-angelo** [kubernetes/cloud-provider-aws#585] opened 2023-03-10 12:09 UTC
**What happened**:
New nodes are not properly added to the LB's target group when using an LB (both ELB and NLB types) with ETP=Local. This is basically a race condition between the node lifecycle controller and the `UpdateLoadbalancer` call. 

In `k8s.io/cloud-provider v0.26.0` the nodes listed during the `UpdateLoadBalancer` call defined ([ref](https://github.com/kubernetes/kubernetes/blob/fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L707)), do not wait for the node to be ready ([ref](https://github.com/kubernetes/kubernetes/blob/fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L931))

which in turn are filtered by: https://github.com/kubernetes/cloud-provider-aws/blob/982e654c1a637dde00f397309a9f56eec6069025/pkg/providers/v1/aws.go#L4901 

and 

https://github.com/kubernetes/cloud-provider-aws/blob/982e654c1a637dde00f397309a9f56eec6069025/pkg/providers/v1/instances.go#L109-L112

In the end the new nodes are skipped and never properly registered on the target group. It is only on the next LB update where the nodes have already received a providerID that they will be added.

**What you expected to happen**:
For the target group to be properly updated when new nodes are added.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a LB service with `externalTrafficPolicy=Local`. Wait for it to be ensured
2. Add a new node to the cluster.
3. Observe

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25.1
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by kmala** [comment] 2023-04-14 23:51
I had created an issue https://github.com/kubernetes/kubernetes/issues/117375 to understand whether such scenarios are considered when making that change.

**Comment by subhankarc** [comment] 2023-04-24 17:50
@kmala https://github.com/kubernetes/kubernetes/issues/117375 seems to be closed ? Is this issue solved on both 1.25 and 1.26 and can it be closed ?

**Comment by kmala** [comment] 2023-04-24 17:52
yes, we can close the issue and the issue is in 1.26 and 1.27 not in 1.25.

**Closed** 2023-08-02 10:26 UTC
Labels: kind/bug, needs-triage
